name: "License Check"

on:
  workflow_call:

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest
    outputs:
      run_cla_workflow: ${{ steps.check_license.outputs.run_cla }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout Org .github Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/.github
          path: .github-org

      - name: Check license
        id: check_license
        shell: bash
        run: |
          # Read licenses from organization's permissive_licenses.json
          if [[ ! -f ".github-org/permissive_licenses.json" ]]; then
            echo "Error: Required file permissive_licenses.json not found in organization's .github repository"
            exit 1
          fi
          
          # Get permissive licenses from JSON
          permissive_licenses=$(jq -r '.permissive[]' ".github-org/permissive_licenses.json")
          
          if [[ $? -ne 0 ]]; then
            echo "Error: Failed to parse permissive_licenses.json"
            exit 1
          fi
          
          # Find any license file
          license_file=$(find . -maxdepth 1 -type f -iname 'license*' -o -iname 'copying*' | head -n 1)
          
          if [[ -n "$license_file" ]]; then
            echo "Found license file: $license_file"
            
            # Create pattern for grep
            pattern=$(echo "$permissive_licenses" | paste -sd '|')
            
            # Check for any permissive license in first 20 lines
            if head -n 20 "$license_file" | grep -q -i -E "$pattern"; then
              echo "run_cla=false" >> "$GITHUB_OUTPUT"
              echo "Permissive license found. CLA will be skipped."
            else
              echo "run_cla=true" >> "$GITHUB_OUTPUT"
              echo "Non-permissive license found. CLA will be triggered."
            fi
          else
            echo "run_cla=true" >> "$GITHUB_OUTPUT"
            echo "No license file found. CLA will be triggered."
          fi

      - name: Call CLA Workflow
        if: steps.check_license.outputs.run_cla == 'true'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://github.com/cla-assistant/github-action/blob/master/SAPCLA.md'
          branch: 'main'
          allowlist: user1,bot*
