name: "License Check"

on:
  workflow_call:
    inputs:
      pull-request-target:
        required: true
        type: boolean
        default: true
  pull_request_target:
    types: [opened, synchronize, closed]
  issue_comment:
    types: [created]

jobs:
  check-and-trigger:
    if: |
      (github.event_name == 'pull_request_target' && inputs.pull-request-target) ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    runs-on: ubuntu-latest
    steps:
      - name: Initialize workflow state
        id: init
        run: |
          # Set event type flag
          echo "is_comment=${{ github.event_name == 'issue_comment' }}" >> "$GITHUB_OUTPUT"
          
          # For comments, check if it's a CLA-related command
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            comment="${{ github.event.comment.body }}"
            if [[ "$comment" == "recheck" || "$comment" == "I have read the CLA Document and I hereby sign the CLA" ]]; then
              echo "is_cla_command=true" >> "$GITHUB_OUTPUT"
            else
              echo "is_cla_command=false" >> "$GITHUB_OUTPUT"
            fi
          fi

      # Only run license checks for pull request events
      - name: Checkout code
        if: steps.init.outputs.is_comment != 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Checkout Org .github Repo
        if: steps.init.outputs.is_comment != 'true'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/.github
          path: .github-org

      - name: Check license
        if: steps.init.outputs.is_comment != 'true'
        id: license_check
        run: |
          if [[ ! -f ".github-org/permissive_licenses.json" ]]; then
            echo "Error: Required file permissive_licenses.json not found"
            exit 1
          fi

          license_file=$(find . -maxdepth 1 -type f -iname 'license*' -o -iname 'copying*' | head -n 1)
          if [[ -n "$license_file" ]]; then
            echo "Found license file: $license_file"
            
            pattern=$(jq -r '.permissive[]' ".github-org/permissive_licenses.json" | while read -r license; do 
              echo "\b${license}\b"
            done | paste -sd '|')
            
            if head -n 20 "$license_file" | grep -q -E "$pattern"; then
              echo "needs_cla=false" >> "$GITHUB_OUTPUT"
            else
              echo "needs_cla=true" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "No license file found"
            echo "needs_cla=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Call CLA Workflow
        if: |
          (steps.init.outputs.is_comment == 'true' && steps.init.outputs.is_cla_command == 'true') ||
          (steps.init.outputs.is_comment != 'true' && steps.license_check.outputs.needs_cla == 'true')
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://github.com/cla-assistant/github-action/blob/master/SAPCLA.md'
          branch: 'main'
          allowlist: user1,bot*
          name: "License Check"
          remote-repository-name: .github
          signed-commit-message: '${{ github.actor }} has signed the CLA in ${{ github.repository_owner }}/${{ github.repository }}#${{ github.event.pull_request }}'
          custom-notsigned-prcomment: 'All non-permissive licensed projects require a signed CLA--please read and sign our CLA: $pathToCLADocument'
          custom-pr-sign-comment: '${{ github.event.pull_request.user.login }} have read the Developer Terms Document and I hereby accept the Terms'
