name: "License Check"

on:
  workflow_call:

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest
    outputs:
      run_cla_workflow: ${{ steps.check_license.outputs.run_cla }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 for better performance

      - name: Checkout Org .github Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/.github
          path: .github-org
          sparse-checkout: |
            permissive_licenses.json  # Only checkout the needed file
          sparse-checkout-cone-mode: false

      - name: Check license
        id: check_license
        shell: bash
        run: |
          # Find any license file using a single find command
          license_file=$(find . -maxdepth 1 -type f -iname 'license*' -o -iname 'copying*' | head -n 1)
          
          if [[ -n "$license_file" ]]; then
            echo "Found license file: $license_file"
            
            # Read licenses directly from JSON and process in a single command
            permissive_licenses=$(jq -r '.permissive[]' .github-org/permissive_licenses.json)
            
            # Create pattern for grep to search all licenses at once
            pattern=$(echo "$permissive_licenses" | paste -sd '|')
            
            # Check for any permissive license in first 20 lines using a single grep
            if head -n 20 "$license_file" | grep -q -i -E "$pattern"; then
              echo "run_cla=false" >> "$GITHUB_OUTPUT"
              echo "Permissive license found. CLA will be skipped."
            else
              echo "run_cla=true" >> "$GITHUB_OUTPUT"
              echo "Non-permissive license found. CLA will be triggered."
            fi
          else
            echo "run_cla=true" >> "$GITHUB_OUTPUT"
            echo "No license file found. CLA will be triggered."
          fi

      - name: Call CLA Workflow
        if: steps.check_license.outputs.run_cla == 'true'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://github.com/cla-assistant/github-action/blob/master/SAPCLA.md'
          branch: 'main'
          allowlist: user1,bot*
